/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as CollegeHubRouteImport } from './routes/college-hub'
import { Route as ResourcesRouteImport } from './routes/resources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeHubRoute = CollegeHubRouteImport.update({
  id: '/college-hub',
  path: '/college-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/college-hub': typeof CollegeHubRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/college-hub': typeof CollegeHubRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/college-hub': typeof CollegeHubRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/campus' | '/college-hub' | '/resources'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campus' | '/college-hub' | '/resources'
  id: '__root__' | '/' | '/campus' | '/college-hub' | '/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampusRoute: typeof CampusRoute
  CollegeHubRoute: typeof CollegeHubRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college-hub': {
      id: '/college-hub'
      path: '/college-hub'
      fullPath: '/college-hub'
      preLoaderRoute: typeof CollegeHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampusRoute: CampusRoute,
  CollegeHubRoute: CollegeHubRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
