/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as CollegeHubRouteImport } from './routes/college-hub'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as DeadlinesRouteImport } from './routes/deadlines'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as MistakeBankRouteImport } from './routes/mistake-bank'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PaperAnalyzerRouteImport } from './routes/paper-analyzer'
import { Route as PrerequisitesRouteImport } from './routes/prerequisites'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TeamFinderRouteImport } from './routes/team-finder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeHubRoute = CollegeHubRouteImport.update({
  id: '/college-hub',
  path: '/college-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlinesRoute = DeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakeBankRoute = MistakeBankRouteImport.update({
  id: '/mistake-bank',
  path: '/mistake-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperAnalyzerRoute = PaperAnalyzerRouteImport.update({
  id: '/paper-analyzer',
  path: '/paper-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrerequisitesRoute = PrerequisitesRouteImport.update({
  id: '/prerequisites',
  path: '/prerequisites',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamFinderRoute = TeamFinderRouteImport.update({
  id: '/team-finder',
  path: '/team-finder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/campus': typeof CampusRoute
  '/college-hub': typeof CollegeHubRoute
  '/community': typeof CommunityRoute
  '/competitions': typeof CompetitionsRoute
  '/deadlines': typeof DeadlinesRoute
  '/learning': typeof LearningRoute
  '/mistake-bank': typeof MistakeBankRoute
  '/opportunities': typeof OpportunitiesRoute
  '/paper-analyzer': typeof PaperAnalyzerRoute
  '/prerequisites': typeof PrerequisitesRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/team-finder': typeof TeamFinderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/campus': typeof CampusRoute
  '/college-hub': typeof CollegeHubRoute
  '/community': typeof CommunityRoute
  '/competitions': typeof CompetitionsRoute
  '/deadlines': typeof DeadlinesRoute
  '/learning': typeof LearningRoute
  '/mistake-bank': typeof MistakeBankRoute
  '/opportunities': typeof OpportunitiesRoute
  '/paper-analyzer': typeof PaperAnalyzerRoute
  '/prerequisites': typeof PrerequisitesRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/team-finder': typeof TeamFinderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/campus': typeof CampusRoute
  '/college-hub': typeof CollegeHubRoute
  '/community': typeof CommunityRoute
  '/competitions': typeof CompetitionsRoute
  '/deadlines': typeof DeadlinesRoute
  '/learning': typeof LearningRoute
  '/mistake-bank': typeof MistakeBankRoute
  '/opportunities': typeof OpportunitiesRoute
  '/paper-analyzer': typeof PaperAnalyzerRoute
  '/prerequisites': typeof PrerequisitesRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/team-finder': typeof TeamFinderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/campus'
    | '/college-hub'
    | '/community'
    | '/competitions'
    | '/deadlines'
    | '/learning'
    | '/mistake-bank'
    | '/opportunities'
    | '/paper-analyzer'
    | '/prerequisites'
    | '/projects'
    | '/resources'
    | '/team-finder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/campus'
    | '/college-hub'
    | '/community'
    | '/competitions'
    | '/deadlines'
    | '/learning'
    | '/mistake-bank'
    | '/opportunities'
    | '/paper-analyzer'
    | '/prerequisites'
    | '/projects'
    | '/resources'
    | '/team-finder'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/campus'
    | '/college-hub'
    | '/community'
    | '/competitions'
    | '/deadlines'
    | '/learning'
    | '/mistake-bank'
    | '/opportunities'
    | '/paper-analyzer'
    | '/prerequisites'
    | '/projects'
    | '/resources'
    | '/team-finder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  CampusRoute: typeof CampusRoute
  CollegeHubRoute: typeof CollegeHubRoute
  CommunityRoute: typeof CommunityRoute
  CompetitionsRoute: typeof CompetitionsRoute
  DeadlinesRoute: typeof DeadlinesRoute
  LearningRoute: typeof LearningRoute
  MistakeBankRoute: typeof MistakeBankRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PaperAnalyzerRoute: typeof PaperAnalyzerRoute
  PrerequisitesRoute: typeof PrerequisitesRoute
  ProjectsRoute: typeof ProjectsRoute
  ResourcesRoute: typeof ResourcesRoute
  TeamFinderRoute: typeof TeamFinderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college-hub': {
      id: '/college-hub'
      path: '/college-hub'
      fullPath: '/college-hub'
      preLoaderRoute: typeof CollegeHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlines': {
      id: '/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof DeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistake-bank': {
      id: '/mistake-bank'
      path: '/mistake-bank'
      fullPath: '/mistake-bank'
      preLoaderRoute: typeof MistakeBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper-analyzer': {
      id: '/paper-analyzer'
      path: '/paper-analyzer'
      fullPath: '/paper-analyzer'
      preLoaderRoute: typeof PaperAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prerequisites': {
      id: '/prerequisites'
      path: '/prerequisites'
      fullPath: '/prerequisites'
      preLoaderRoute: typeof PrerequisitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-finder': {
      id: '/team-finder'
      path: '/team-finder'
      fullPath: '/team-finder'
      preLoaderRoute: typeof TeamFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  CampusRoute: CampusRoute,
  CollegeHubRoute: CollegeHubRoute,
  CommunityRoute: CommunityRoute,
  CompetitionsRoute: CompetitionsRoute,
  DeadlinesRoute: DeadlinesRoute,
  LearningRoute: LearningRoute,
  MistakeBankRoute: MistakeBankRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PaperAnalyzerRoute: PaperAnalyzerRoute,
  PrerequisitesRoute: PrerequisitesRoute,
  ProjectsRoute: ProjectsRoute,
  ResourcesRoute: ResourcesRoute,
  TeamFinderRoute: TeamFinderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
