/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as CollegeHubRouteImport } from './routes/college-hub'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as MistakeBankRouteImport } from './routes/mistake-bank'
import { Route as PaperAnalyzerRouteImport } from './routes/paper-analyzer'
import { Route as PrerequisitesRouteImport } from './routes/prerequisites'
import { Route as ResourcesRouteImport } from './routes/resources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeHubRoute = CollegeHubRouteImport.update({
  id: '/college-hub',
  path: '/college-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakeBankRoute = MistakeBankRouteImport.update({
  id: '/mistake-bank',
  path: '/mistake-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperAnalyzerRoute = PaperAnalyzerRouteImport.update({
  id: '/paper-analyzer',
  path: '/paper-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrerequisitesRoute = PrerequisitesRouteImport.update({
  id: '/prerequisites',
  path: '/prerequisites',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/college-hub': typeof CollegeHubRoute
  '/learning': typeof LearningRoute
  '/mistake-bank': typeof MistakeBankRoute
  '/paper-analyzer': typeof PaperAnalyzerRoute
  '/prerequisites': typeof PrerequisitesRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/college-hub': typeof CollegeHubRoute
  '/learning': typeof LearningRoute
  '/mistake-bank': typeof MistakeBankRoute
  '/paper-analyzer': typeof PaperAnalyzerRoute
  '/prerequisites': typeof PrerequisitesRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/college-hub': typeof CollegeHubRoute
  '/learning': typeof LearningRoute
  '/mistake-bank': typeof MistakeBankRoute
  '/paper-analyzer': typeof PaperAnalyzerRoute
  '/prerequisites': typeof PrerequisitesRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campus'
    | '/college-hub'
    | '/learning'
    | '/mistake-bank'
    | '/paper-analyzer'
    | '/prerequisites'
    | '/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campus'
    | '/college-hub'
    | '/learning'
    | '/mistake-bank'
    | '/paper-analyzer'
    | '/prerequisites'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/campus'
    | '/college-hub'
    | '/learning'
    | '/mistake-bank'
    | '/paper-analyzer'
    | '/prerequisites'
    | '/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampusRoute: typeof CampusRoute
  CollegeHubRoute: typeof CollegeHubRoute
  LearningRoute: typeof LearningRoute
  MistakeBankRoute: typeof MistakeBankRoute
  PaperAnalyzerRoute: typeof PaperAnalyzerRoute
  PrerequisitesRoute: typeof PrerequisitesRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college-hub': {
      id: '/college-hub'
      path: '/college-hub'
      fullPath: '/college-hub'
      preLoaderRoute: typeof CollegeHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistake-bank': {
      id: '/mistake-bank'
      path: '/mistake-bank'
      fullPath: '/mistake-bank'
      preLoaderRoute: typeof MistakeBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper-analyzer': {
      id: '/paper-analyzer'
      path: '/paper-analyzer'
      fullPath: '/paper-analyzer'
      preLoaderRoute: typeof PaperAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prerequisites': {
      id: '/prerequisites'
      path: '/prerequisites'
      fullPath: '/prerequisites'
      preLoaderRoute: typeof PrerequisitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampusRoute: CampusRoute,
  CollegeHubRoute: CollegeHubRoute,
  LearningRoute: LearningRoute,
  MistakeBankRoute: MistakeBankRoute,
  PaperAnalyzerRoute: PaperAnalyzerRoute,
  PrerequisitesRoute: PrerequisitesRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
