// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function isServerOnlySupabaseKey(value: string): boolean {
  if (value.startsWith("sb_secret_")) return true;
  const payload = value.split(".")[1];
  if (!payload) return false;
  try {
    const base64 = payload.replace(/-/g, "+").replace(/_/g, "/");
    const claims = JSON.parse(atob(base64.padEnd(Math.ceil(base64.length / 4) * 4, "=")));
    return claims.role === "service_role";
  } catch {
    return false;
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Browser VITE_* values take precedence. Vite also injects only the two
  // explicitly public SUPABASE_* values as a fallback for Render builds.
  const publicEnv = import.meta.env;
  const serverEnv = typeof process === "undefined" ? undefined : process.env;
  const SUPABASE_URL =
    publicEnv["VITE_SUPABASE_URL"] ||
    // @ts-expect-error This exact public value is injected by vite.config.ts.
    import.meta.env.SUPABASE_URL ||
    serverEnv?.["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    publicEnv["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    // @ts-expect-error This exact public value is injected by vite.config.ts.
    import.meta.env.SUPABASE_PUBLISHABLE_KEY ||
    serverEnv?.["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Set the public browser values at build time or provide the corresponding SUPABASE_* values to Render.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (isServerOnlySupabaseKey(SUPABASE_PUBLISHABLE_KEY)) {
    throw new Error(
      "The public Supabase client requires a publishable/anon key, not a server-only secret/service-role key.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
